[package]
name = "fused_gpu"
version = "0.1.0"
edition = "2024"
readme = "README.md"

[profile.dev]
incremental = false

[profile.release]
incremental = false
opt-level = 3
codegen-units = 1
debug = true

[profile.release.package."*"]
incremental = false
opt-level = 3
codegen-units = 1
debug = false

[features]
default = ["wgsl", "standard_ops"]

std = []
wgsl = ["std", "dep:wgpu"]
standard_ops = []

[[example]]
name = "matmul_chain3"
required-features = ["standard_ops", "wgsl"]

[[test]]
name = "std_wgsl"
required-features = ["standard_ops", "wgsl"]

[dependencies]
briny = "0.4.1"

[dev-dependencies]
pollster = "0.4.0"

[target.'cfg(target_family = "windows")'.dependencies.wgpu]
version = "30.0.0"
default-features = false
features = ["wgsl", "dx12", "vulkan"]
optional = true

[target.'cfg(target_os = "macos")'.dependencies.wgpu]
version = "30.0.0"
default-features = false
features = ["wgsl", "metal", "vulkan-portability", "angle"]
optional = true

[target.'cfg(target_os = "linux")'.dependencies.wgpu]
version = "30.0.0"
default-features = false
features = ["wgsl", "vulkan", "gles"]
optional = true

[target.'cfg(any(target_arch = "wasm32", target_arch = "wasm64", target_os = "wasi"))'.dependencies.wgpu]
version = "30.0.0"
default-features = false
features = ["wgsl", "webgpu", "webgl"]
optional = true

[target.'cfg(not(any(target_arch = "wasm32", target_arch = "wasm64", target_os = "wasi", target_os = "linux", target_os = "macos", target_family = "windows")))'.dependencies.wgpu]
version = "30.0.0"
default-features = false
features = [
    "std",
    "parking_lot",
    "vulkan",
    "vulkan-portability",
    "angle",
    "gles",
    "dx12",
    "metal",
    "wgsl",
    "webgpu",
]
optional = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
targets = [
  "aarch64-apple-ios",
  "aarch64-linux-android",
  "wasm32-wasip1",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-gnu",
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-dragonfly",
  "x86_64-unknown-freebsd",
  "x86_64-unknown-illumos",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-netbsd",
  "x86_64-unknown-openbsd",
  "x86_64-unknown-hermit",
]
